### ISSUE TITLE
US1  List of Routes

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/pfad-keeper-app#1]
## Value Proposition

**As a** user
**I want** to see a list of my routes
**so that** I can see where have I been or where am I going
​

## Description

![Image](https://github.com/AlexDernov/pfad-keeper-app/assets/127208943/b5b9962a-81c4-4977-b521-8416b1f2b35b)

## Acceptance Criteria

- [x]  All routes are displayed as a list 👁️
- [x]  Listitem has the same height as content 
- [x]  Each locations's map placeholder is displayed 👁️
- [x]  Each locations's title is displayed 👁️
- [x]  Each locations's data is displayed 👁️

## Tasks

- [x]  Open  new branch
- [x]  Create db/models/
- [x]  Create Backend: models Route, RouteRepo, RouteService, RouteController 
- [x]  Create Tests (Integration & Unit)
Connect  Back- und Frontend:
- [x]  Fetch all route data from MongoDB Localhost using SWR State, so that routes are available on all previous pages
- [x]  Create the component RoutesList to render a list.
- [x] Create NavBar and Homepage
- [x]  Style the components

## Complexity

M
