### ISSUE TITLE
US2 Add, edit and delete Route

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/pfad-keeper-app#3]
## Value Proposition

**As a** user
**I want** to handle my routes
**so that** I can edit, add and delete them

## Acceptance Criteria

- [x] Clicking "New Route" button switches to the AddPage
- [x] Input fields "name" and "date" are displayed
- [x] "Save" button is displayed
- [x] Clicking the "Save" button saved the data in the locations collection on MongoDB 

- [x] Details page of route has an "Edit" buttons
- [x] Clicking on "Edit" button allows to edit the route

- [x] Details page of route  has a "Delete" button
- [x] Clicking on "Delete" button deletes a message from the list and from the MongoDB

## Tasks
- [x] Create new branch
- [x] Create an NewRoute component
- [x] Create RouteForm component
- [x] Create an "Edit" and "Delete" buttons
- [x]  Add fetch.post and fetch.put 

## Complexity

S
