### ISSUE TITLE
US3 Interactive Map

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/pfad-keeper-app#6]
## Value Proposition

**As a** user
**I want to** have an interactive map 
**so that** I can plan a route by placing markers on the map
​

## Acceptance Criteria

- [ ] The interactive map on the details page is displayed
- [ ] The map is zoomable 
- [ ] Selecting start and end points leaves markers on the map.
- [ ] A route is laid between markers
​

## Tasks

- [ ]  Create a new branch
- [ ]  Install the MapBox library
- [ ]  Rewriting of the Map component 
- [ ]  Customize the required options of the interactive map

## Complexity

 XL
